version: "3"
services:
    db:
        image: "postgres"
        # ports:
        #       - "5432:5432"
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
        networks:
          - cs-network
        
    web:
       # build: .
        image: webapi
        ports:
            - "5000:80"
        depends_on:
            - db
        networks:
          - cs-network
        environment:
          DATABASE_URL: Host=db;Port=5432;Username=postgres;Password=password;Database=todos_cs;
networks:
  cs-network:
    driver: bridge


